<?php
// Include database config file => to get our PDO object 
require_once 'include/db_connect.php';

/* 
Assignment#3:
No Hard coded values :-(
$first_name="Alex";
$last_name="Chow";

$email=
$password=
*/

// PHPStorm IDE (1 year free student)

// Assuming that we received these info from a user form
$postTitle = "Adobe Dreamweaver"; // $_POST['title']
$postBody ="Adobe Dreamweaver is an integrated development environment. 
It can be used by pure designers who don't know how to write HTML 
or by developer who want to focus on writing their code.";
$postAuthor = "Stephanie Stephens";
$isPublished = 0;
$postCreatedDate = "2021-10-07";

// Below is just a copy of INSERT Statement Template Generated by MySQL (phpMyAdmin):
/*
INSERT INTO `posts`
(`post_id`, `title`, `body`, `author`, `published`, `released`) 
VALUES ('[value-1]','[value-2]','[value-3]','[value-4]','[value-5]','[value-6]')
*/

// Bad idea to place the user's input immediately
/* 
$sql='INSERT INTO posts (title, body, author, published, released)
VALUES('$postTitle','$postBody','$postAuthor','$isPublished','$postCreatedDate');'
*/

/* 
Using the prepare statement:
- Anonymous Positional (?) => ?
- Named Identifier => :ident_name (any name that makes sense to you)
*/
$sql='INSERT INTO posts (title, body, author, published, released)
VALUES(:title, :article, :author, :published, :released)';

$stmt = $pdo->prepare($sql);

/* 
PHP.NET: execute() => Returns "true" on success or "false" on failure.

PHP.NET: rowCount() => returns the number of rows affected 
by the last DELETE, INSERT, or UPDATE statement 
executed by the corresponding PDOStatement object.

Link: https://www.php.net/manual/en/pdostatement.rowcount
*/

$isInserted= $stmt->execute(
    [
        'title'=>$postTitle,
        'article' => $postBody ,
        'author' => $postAuthor ,
        'published'=> $isPublished,
        'released'=> $postCreatedDate
    ]);


// var_dump($x); // bool(true)
if ($isInserted) {
    echo "<br>A new post has been added!";
} else {
    echo "<br>Sorry Inserting a new post is failed!";
}
echo "<hr>";



